#pragma once

#include <QString>
#include <QStringList>

// Variables autogenerated from the current git-revision upon building the project
extern "C" {
extern const char* RIPES_GIT_VERSION;
}

static inline QString getRipesVersion() {
    return QString(RIPES_GIT_VERSION);
}
