#include <QDir>
#include <QProcess>
#include <QResource>
#include <QStringList>
#include <QtTest/QTest>

#include <optional>
#include <ranges>

#include "processorhandler.h"
#include "processorregistry.h"

#include "edittab.h"
#include "isa/rvisainfo_common.h"
#include "programloader.h"
#include "ripessettings.h"

/**
 * Ripes co-simulation
 * For a given test program, executes a reference model (RVSS) to generate a
 * trace of register modifications. Then, the target processor is simulated, and
 * its register trace is compared to the reference trace. From this, we can
 * detect whether (and where) register state divergence occurs, which indicates
 * an error in a processor implementation
 */

using namespace Ripes;
using namespace vsrtl::core;
struct RegisterChange {
  std::string_view fileName;
  unsigned index;
  VInt newValue;
};

// Maximum cycle count
static constexpr unsigned s_maxCycles = 1000000;
using Registers = std::map<std::string_view, std::map<unsigned, VInt>>;
struct TraceEntry {
  Registers regs;
  unsigned long cycle;
  AInt pc;
};

using Trace = std::vector<TraceEntry>;

// Reference model
// All tests will be compared against the trace generated by this processor
// model.
static constexpr ProcessorID s_referenceModel = ProcessorID::RV32_SS;

// Test selection
// s_testFiles denotes all of the test files that will be included in the
// cosimulation run for each processor.
const QString s_testdir = RISCV32_TEST_DIR;
const std::vector<LoadFileParams> s_testFiles = {
    LoadFileParams{QString(s_testdir + QDir::separator() +
                           "../../examples/assembly/complexMul.s"),
                   SourceType::Assembly, 0, 0},
    LoadFileParams{QString(s_testdir + QDir::separator() +
                           "../../examples/assembly/factorial.s"),
                   SourceType::Assembly, 0, 0},
    LoadFileParams{QString(s_testdir + QDir::separator() +
                           "../../examples/ELF/RanPi-RV32"),
                   SourceType::ExternalELF, 0, 0}};

class tst_Cosimulate : public QObject {
  Q_OBJECT

public:
  explicit tst_Cosimulate() {}

private:
  void cosimulate(const ProcessorID &id, const QStringList &extensions);
  const Trace &generateReferenceTrace(const QStringList &extensions);
  void trapHandler();
  void executeSimulator(Trace &outTrace, const Trace *refTrace = nullptr);
  Registers dumpRegs();
  QString generateErrorReport(const std::vector<RegisterChange> &change,
                              const TraceEntry &lhs,
                              const TraceEntry &rhs) const;
  void loadCurrentTest();

  bool m_stop = false;
  QString m_err;
  LoadFileParams m_currentTest;
  ProgramLoader *m_loader;

  std::map<QString, Trace> m_referenceTraces;

private slots:
  /**
   * PROCESSOR MODELS TO TEST
   * Each of the following functions shall indicate a processor model to
   * co-simulate.
   */
  void testRV6SDual() { cosimulate(ProcessorID::RV32_6S_DUAL, {"M"}); }
  void testRV5S() { cosimulate(ProcessorID::RV32_5S, {"M"}); }
  void testRV5SNoFW() { cosimulate(ProcessorID::RV32_5S_NO_FW, {"M"}); }
  void testRV5MC2M() { cosimulate(ProcessorID::RV32_5MC_2M, {"M"}); }
  void testRV5MC1M() { cosimulate(ProcessorID::RV32_5MC_1M, {"M"}); }
};

void tst_Cosimulate::trapHandler() {
  auto reg =
      ProcessorHandler::get()->getProcessor()->implementsISA()->syscallReg();
  assert(reg.has_value());

  unsigned status = ProcessorHandler::get()->getProcessor()->getRegister(
      reg->file->regFileName(), reg->index);

  /// @todo: Generalize this by having ISA report exit syscall codes
  if (status == RVABI::SysCall::Exit || status == RVABI::SysCall::Exit2) {
    m_stop = true;
  }
}

Registers tst_Cosimulate::dumpRegs() {
  Registers regs;
  for (const auto &regFile :
       ProcessorHandler::get()->currentISA()->regInfos()) {
    regs[regFile->regFileName()] = {};
    for (unsigned i = 0; i < regFile->regCnt(); i++) {
      regs[regFile->regFileName()][i] = ProcessorHandler::get()->getProcessor()
        ->getRegister(regFile->regFileName(), i);
    }
  }
  return regs;
}

/// check whether the test registers deviate from the reference registers. 
/// register files (as well as register indices) which are not included in 
/// the reference are ignored.
/// returns a vector of the register changes between the reference and test 
/// state, if any such changes exist. Otherwise, returns std::nullopt.
std::optional<std::vector<RegisterChange>> registerChange(
  const Registers &reference, 
  const Registers &test
) {
  std::vector<RegisterChange> changes;
  for (const auto &[regFileName, regValues] : reference) {
    for (const auto &[idx, value] : regValues) {
      Q_ASSERT(test.contains(regFileName));
      if (value != test.at(regFileName).at(idx)) {
        changes.push_back({regFileName, idx, test.at(regFileName).at(idx)});
      }
    }
  }

  if (changes.size() > 0) {
    return {changes};
  } else {
    return std::nullopt;
  }
}


QString tst_Cosimulate::generateErrorReport(const std::vector<RegisterChange> &changes,
                                            const TraceEntry &reference,
                                            const TraceEntry &test) const {
  QString err;
  err += "\nRegister change discrepancy detected while executing test: " +
         m_currentTest.filepath;
  
  err += "\n\nUnexpected change was:\n";
  for(const auto &change : changes) {
    auto regInfo = ProcessorHandler::get()->currentISA()->regInfo(change.fileName);
    err += "\t" + QString(change.fileName.data()) + ": ";
    err += (*regInfo)->regName(change.index);
    err += " = 0x" + QString::number(change.newValue, 16) + "\n";
  }

  err += "\nTest processor state: \t\tPC: 0x" + QString::number(test.pc, 16) +
        "\t Cycle #: " + QString::number(test.cycle);
  err += "\nReference processor state: \tPC: 0x" + QString::number(reference.pc, 16) +
        "\t Cycle #: " + QString::number(reference.cycle);
  err += "\n";

  std::vector<RegisterChange> regChanges 
    = registerChange(reference.regs, test.regs).value_or(std::vector<RegisterChange>{});
  for (const auto &change : regChanges) {
    auto regInfo = ProcessorHandler::get()->currentISA()->regInfo(change.fileName);
    err += "Difference in register " + QString(change.fileName.data()) + ": ";
    err += (*regInfo)->regName(change.index);
    err += "\texpected: 0x" + QString::number(reference.regs.at(change.fileName).at(change.index), 16) +
           "\tactual: 0x" + QString::number(test.regs.at(change.fileName).at(change.index), 16) + "\n";
  }

  return err;
}

/**
 * @brief tst_Cosimulate::executeSimulator
 * Runs the currently loaded simulator on the currently loaded program,
 * generating a register trace while doing so. If @p refTrace is provided, the
 * generated trace is compared to the reference trace and the test fails if a
 * discrepancy is detected.
 */
void tst_Cosimulate::executeSimulator(Trace &trace, const Trace *refTrace) {
  m_loader->loadTest(m_currentTest);

  // Override the ProcessorHandler's ECALL handling. In doing so, we can hook
  // into when the EXIT syscall was executed, to verify whether the correct test
  // value was reached.
  ProcessorHandler::get()->getProcessorNonConst()->trapHandler = [this] {
    trapHandler();
  };

  m_stop = false;
  m_err = QString();
  bool maxCyclesReached = false;
  unsigned cycles = 0;
  trace.emplace_back(
      dumpRegs(), cycles,
      ProcessorHandler::get()->getProcessor()->getPcForStage({0, 0})
  );

  std::vector<std::string_view> observedRegFiles;
  decltype(refTrace->begin()) cmpRegState;
  if (refTrace) {
    cmpRegState = refTrace->begin();
    // since dumpRegs() always returns the same set of register files for all trace entries:
    const auto regFilesView = cmpRegState->regs | std::views::keys;
    observedRegFiles.assign(regFilesView.begin(), regFilesView.end());
    cmpRegState++; // skip initial state
  }

  Registers preRegs = dumpRegs();

  do {
    ProcessorHandler::get()->getProcessorNonConst()->clock();
    cycles++;

    Registers regs = dumpRegs();
    auto optRegChanges = registerChange(preRegs, regs);
    // Detect change in current register state
    if (optRegChanges.has_value()) {
      trace.emplace_back(
          regs, cycles,
          ProcessorHandler::get()->getProcessor()->getPcForStage({0, 0})
      );

      // Check whether change corresponds to expected change in comparison
      // trace. regChange might contain multiple register changes (for
      // processors that can commit >1 instruction per cycle). So we try to
      // locate each of the changes in the next expected register set
      // (cmpRegStatePtr), until we have accounted for all register changes. If
      // we incremented the expected register set, but did not find an
      // accompanying register change, then we've reached a point of divergence.
      if (refTrace != nullptr) {
        std::vector<RegisterChange> regChanges = std::move(optRegChanges.value());

        // filter out register files which are not included in the reference trace
        for (auto it = regChanges.begin(); it != regChanges.end();) {
          if (std::ranges::find(observedRegFiles, it->fileName) == observedRegFiles.end()) {
            it = regChanges.erase(it);
          } else {
            ++it;
          }
        }
        
        // try matching each register change to an uninterrupted sequence of reference trace register states
        while(regChanges.size() > 0 && cmpRegState != refTrace->end()) {
          bool foundMatch = false;

          for (auto regIt = regChanges.begin(); regIt != regChanges.end(); ++regIt) {
            if (cmpRegState->regs.at(regIt->fileName).at(regIt->index) == regIt->newValue) {
              regChanges.erase(regIt);
              foundMatch = true;
              break;
            }
          }

          if (foundMatch) {
            ++cmpRegState;
          } else {
            // if we reached a state in the reference trace which does not contain any of the register changes, then we have a discrepancy
            const QString err = generateErrorReport(regChanges, *cmpRegState, trace.back());
            QFAIL(err.toStdString().c_str());
          }
        }
      }
    }
    preRegs = regs;

    maxCyclesReached = cycles >= s_maxCycles;
    m_stop |=
        maxCyclesReached || ProcessorHandler::get()->getProcessor()->finished();
  } while (!m_stop);

  if (maxCyclesReached) {
    QFAIL("Maximum cycles reached");
  }
}

/**
 * @brief tst_Cosimulate::generateTrace
 * Executes program @p spProgram on the single-cycle processor model, to
 * generate a reference trace.
 */
const Trace &
tst_Cosimulate::generateReferenceTrace(const QStringList &extensions) {
  auto refTrace = m_referenceTraces.find(m_currentTest.filepath);
  if (refTrace == m_referenceTraces.end()) {
    std::cout << "First time running test; generating reference trace..."
              << std::endl;
    ProcessorHandler::get()->selectProcessor(s_referenceModel, extensions);
    Trace trace;
    executeSimulator(trace);
    m_referenceTraces[m_currentTest.filepath] = trace;
    refTrace = m_referenceTraces.find(m_currentTest.filepath);
  }
  return refTrace->second;
}

/**
 * @brief tst_Cosimulate::cosimulate
 * Cosimulate a given processor with a reference model.
 * The cosimulation is quite inefficient, since we don't concurrently execute
 * two processors but rather generate a reference trace from a reference model,
 * and then execute a test model, generate a trace for this, and comprare this
 * trace with the reference trace. The reason for this is, that only a single
 * processor model can be instantiated at once in Ripes, due to the static
 * nature of the ProcessorHandler.
 */
void tst_Cosimulate::cosimulate(const ProcessorID &id,
                                const QStringList &extensions) {
  m_loader = new ProgramLoader();
  for (const auto &test : s_testFiles) {
    m_currentTest = test;
    std::cout << test.filepath.toStdString() << std::endl;
    auto referenceTrace = generateReferenceTrace(extensions);
    ProcessorHandler::get()->selectProcessor(id, extensions);
    RipesSettings::getObserver(RIPES_GLOBALSIGNAL_REQRESET)->trigger();

    Trace trace;
    std::cout << "Cosimulating... " << std::flush;
    executeSimulator(trace, &referenceTrace);
    std::cout << "PASS!\n" << std::endl;
  }
}

QTEST_MAIN(tst_Cosimulate)
#include "tst_cosimulate.moc"
