#pragma once

#include "elfio/elf_types.hpp"

#include <QMap>
#include <QString>

namespace Ripes {

// clang-format off
const static QMap<unsigned, QString> s_elfMachineNames{{ELFIO::EM_NONE, "No machine"},
                                                       {ELFIO::EM_M32, "AT&T WE 32100"},
                                                       {ELFIO::EM_SPARC, "SPARC"},
                                                       {ELFIO::EM_386, "Intel 80386"},
                                                       {ELFIO::EM_68K, "Motorola 68000"},
                                                       {ELFIO::EM_88K, "Motorola 88000"},
                                                       {ELFIO::EM_860, "Intel 80860"},
                                                       {ELFIO::EM_MIPS, "MIPS I Architecture"},
                                                       {ELFIO::EM_S370, "IBM System/370 Processor"},
                                                       {ELFIO::EM_MIPS_RS3_LE, "MIPS RS3000 Little-endian"},
                                                       {ELFIO::EM_PARISC, "Hewlett-Packard PA-RISC"},
                                                       {ELFIO::EM_SPARC32PLUS, "Enhanced instruction set SPARC"},
                                                       {ELFIO::EM_960, "Intel 80960"},
                                                       {ELFIO::EM_PPC, "PowerPC"},
                                                       {ELFIO::EM_PPC64, "64-bit PowerPC"},
                                                       {ELFIO::EM_S390, "IBM System/390 Processor"},
                                                       {ELFIO::EM_SPU, "IBM SPU/SPC"},
                                                       {ELFIO::EM_V800, "NEC V800"},
                                                       {ELFIO::EM_FR20, "Fujitsu FR20"},
                                                       {ELFIO::EM_RH32, "TRW RH-32"},
                                                       {ELFIO::EM_RCE, "Motorola RCE"},
                                                       {ELFIO::EM_ARM, "ARM 32-bit architecture (AARCH32)"},
                                                       {ELFIO::EM_SH, "Hitachi SH"},
                                                       {ELFIO::EM_SPARCV9, "SPARC Version 9"},
                                                       {ELFIO::EM_TRICORE, "Siemens TriCore embedded processor"},
                                                       {ELFIO::EM_ARC, "Argonaut RISC Core, Argonaut Technologies Inc."},
                                                       {ELFIO::EM_H8_300, "Hitachi H8/300"},
                                                       {ELFIO::EM_H8_300H, "Hitachi H8/300H"},
                                                       {ELFIO::EM_H8S, "Hitachi H8S"},
                                                       {ELFIO::EM_H8_500, "Hitachi H8/500"},
                                                       {ELFIO::EM_IA_64, "Intel IA-64 processor architecture"},
                                                       {ELFIO::EM_MIPS_X, "Stanford MIPS-X"},
                                                       {ELFIO::EM_COLDFIRE, "Motorola ColdFire"},
                                                       {ELFIO::EM_68HC12, "Motorola M68HC12"},
                                                       {ELFIO::EM_MMA, "Fujitsu MMA Multimedia Accelerator"},
                                                       {ELFIO::EM_PCP, "Siemens PCP"},
                                                       {ELFIO::EM_NCPU, "Sony nCPU embedded RISC processor"},
                                                       {ELFIO::EM_NDR1, "Denso NDR1 microprocessor"},
                                                       {ELFIO::EM_STARCORE, "Motorola Star*Core processor"},
                                                       {ELFIO::EM_ME16, "Toyota ME16 processor"},
                                                       {ELFIO::EM_ST100, "STMicroelectronics ST100 processor"},
                                                       {ELFIO::EM_TINYJ, "Advanced Logic Corp. TinyJ embedded processor family"},
                                                       {ELFIO::EM_X86_64, "AMD x86-64 architecture"},
                                                       {ELFIO::EM_PDSP, "Sony DSP Processor"},
                                                       {ELFIO::EM_PDP10, "Digital Equipment Corp. PDP-10"},
                                                       {ELFIO::EM_PDP11, "Digital Equipment Corp. PDP-11"},
                                                       {ELFIO::EM_FX66, "Siemens FX66 microcontroller"},
                                                       {ELFIO::EM_ST9PLUS, "STMicroelectronics ST9+ 8/16 bit microcontroller"},
                                                       {ELFIO::EM_ST7, "STMicroelectronics ST7 8-bit microcontroller"},
                                                       {ELFIO::EM_68HC16, "Motorola MC68HC16 Microcontroller"},
                                                       {ELFIO::EM_68HC11, "Motorola MC68HC11 Microcontroller"},
                                                       {ELFIO::EM_68HC08, "Motorola MC68HC08 Microcontroller"},
                                                       {ELFIO::EM_68HC05, "Motorola MC68HC05 Microcontroller"},
                                                       {ELFIO::EM_SVX, "Silicon Graphics SVx"},
                                                       {ELFIO::EM_ST19, "STMicroelectronics ST19 8-bit microcontroller"},
                                                       {ELFIO::EM_VAX, "Digital VAX"},
                                                       {ELFIO::EM_CRIS, "Axis Communications 32-bit embedded processor"},
                                                       {ELFIO::EM_JAVELIN, "Infineon Technologies 32-bit embedded processor"},
                                                       {ELFIO::EM_FIREPATH, "Element 14 64-bit DSP Processor"},
                                                       {ELFIO::EM_ZSP, "LSI Logic 16-bit DSP Processor"},
                                                       {ELFIO::EM_MMIX, "Donald Knuth's educational 64-bit processor"},
                                                       {ELFIO::EM_HUANY, "Harvard University machine-independent object files"},
                                                       {ELFIO::EM_PRISM, "SiTera Prism"},
                                                       {ELFIO::EM_AVR, "Atmel AVR 8-bit microcontroller"},
                                                       {ELFIO::EM_FR30, "Fujitsu FR30"},
                                                       {ELFIO::EM_D10V, "Mitsubishi D10V"},
                                                       {ELFIO::EM_D30V, "Mitsubishi D30V"},
                                                       {ELFIO::EM_V850, "NEC v850"},
                                                       {ELFIO::EM_M32R, "Mitsubishi M32R"},
                                                       {ELFIO::EM_MN10300, "Matsushita MN10300"},
                                                       {ELFIO::EM_MN10200, "Matsushita MN10200"},
                                                       {ELFIO::EM_PJ, "picoJava"},
                                                       {ELFIO::EM_OPENRISC, "OpenRISC 32-bit embedded processor"},
                                                       {ELFIO::EM_XTENSA, "Tensilica Xtensa Architecture"},
                                                       {ELFIO::EM_VIDEOCORE, "Alphamosaic VideoCore processor"},
                                                       {ELFIO::EM_TMM_GPP, "Thompson Multimedia General Purpose Processor"},
                                                       {ELFIO::EM_NS32K, "National Semiconductor 32000 series"},
                                                       {ELFIO::EM_TPC, "Tenor Network TPC processor"},
                                                       {ELFIO::EM_SNP1K, "Trebia SNP 1000 processor"},
                                                       {ELFIO::EM_ST200, "STMicroelectronics (www.st.com) ST200 microcontroller"},
                                                       {ELFIO::EM_IP2K, "Ubicom IP2xxx microcontroller family"},
                                                       {ELFIO::EM_MAX, "MAX Processor"},
                                                       {ELFIO::EM_CR, "National Semiconductor CompactRISC microprocessor"},
                                                       {ELFIO::EM_F2MC16, "Fujitsu F2MC16"},
                                                       {ELFIO::EM_MSP430, "Texas Instruments embedded microcontroller msp430"},
                                                       {ELFIO::EM_BLACKFIN, "Analog Devices Blackfin (DSP) processor"},
                                                       {ELFIO::EM_SE_C33, "S1C33 Family of Seiko Epson processors"},
                                                       {ELFIO::EM_SEP, "Sharp embedded microprocessor"},
                                                       {ELFIO::EM_ARCA, "Arca RISC Microprocessor"},
                                                       {ELFIO::EM_UNICORE, "Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University"},
                                                       {ELFIO::EM_EXCESS, "eXcess: 16/32/64-bit configurable embedded CPU"},
                                                       {ELFIO::EM_DXP, "Icera Semiconductor Inc. Deep Execution Processor"},
                                                       {ELFIO::EM_ALTERA_NIOS2, "Altera Nios II soft-core processor"},
                                                       {ELFIO::EM_CRX, "National Semiconductor CompactRISC CRX microprocessor"},
                                                       {ELFIO::EM_XGATE, "Motorola XGATE embedded processor"},
                                                       {ELFIO::EM_C166, "Infineon C16x/XC16x processor"},
                                                       {ELFIO::EM_M16C, "Renesas M16C series microprocessors"},
                                                       {ELFIO::EM_DSPIC30F, "Microchip Technology dsPIC30F Digital Signal Controller"},
                                                       {ELFIO::EM_CE, "Freescale Communication Engine RISC core"},
                                                       {ELFIO::EM_M32C, "Renesas M32C series microprocessors"},
                                                       {ELFIO::EM_TSK3000, "Altium TSK3000 core"},
                                                       {ELFIO::EM_RS08, "Freescale RS08 embedded processor"},
                                                       {ELFIO::EM_ECOG2, "Cyan Technology eCOG2 microprocessor"},
                                                       {ELFIO::EM_SCORE7, "Sunplus S+core7 RISC processor"},
                                                       {ELFIO::EM_DSP24, "New Japan Radio (NJR) 24-bit DSP Processor"},
                                                       {ELFIO::EM_VIDEOCORE3, "Broadcom VideoCore III processor"},
                                                       {ELFIO::EM_LATTICEMICO32, "RISC processor for Lattice FPGA architecture"},
                                                       {ELFIO::EM_SE_C17, "Seiko Epson C17 family"},
                                                       {ELFIO::EM_TI_C6000, "The Texas Instruments TMS320C6000 DSP family"},
                                                       {ELFIO::EM_TI_C2000, "The Texas Instruments TMS320C2000 DSP family"},
                                                       {ELFIO::EM_TI_C5500, "The Texas Instruments TMS320C55x DSP family"},
                                                       {ELFIO::EM_MMDSP_PLUS, "STMicroelectronics 64bit VLIW Data Signal Processor"},
                                                       {ELFIO::EM_MMDSP_PLUS, "STMicroelectronics 64bit VLIW Data Signal Processor"},
                                                       {ELFIO::EM_CYPRESS_M8C, "Cypress M8C microprocessor"},
                                                       {ELFIO::EM_R32C, "Renesas R32C series microprocessors"},
                                                       {ELFIO::EM_TRIMEDIA, "NXP Semiconductors TriMedia architecture family"},
                                                       {ELFIO::EM_QDSP6, "QUALCOMM DSP6 Processor"},
                                                       {ELFIO::EM_8051, "Intel 8051 and variants"},
                                                       {ELFIO::EM_STXP7X, "STMicroelectronics STxP7x family of configurable and extensible RISC processors"},
                                                       {ELFIO::EM_NDS32, "Andes Technology compact code size embedded RISC processor family"},
                                                       {ELFIO::EM_ECOG1, "Cyan Technology eCOG1X family"},
                                                       {ELFIO::EM_ECOG1X, "Cyan Technology eCOG1X family"},
                                                       {ELFIO::EM_MAXQ30, "Dallas Semiconductor MAXQ30 Core Micro-controllers"},
                                                       {ELFIO::EM_XIMO16, "New Japan Radio (NJR) 16-bit DSP Processor"},
                                                       {ELFIO::EM_MANIK, "M2000 Reconfigurable RISC Microprocessor"},
                                                       {ELFIO::EM_CRAYNV2, "Cray Inc. NV2 vector architecture"},
                                                       {ELFIO::EM_RX, "Renesas RX family"},
                                                       {ELFIO::EM_METAG, "Imagination Technologies META processor architecture"},
                                                       {ELFIO::EM_MCST_ELBRUS, "MCST Elbrus general purpose hardware architecture"},
                                                       {ELFIO::EM_ECOG16, "Cyan Technology eCOG16 family"},
                                                       {ELFIO::EM_CR16, "National Semiconductor CompactRISC CR16 16-bit microprocessor"},
                                                       {ELFIO::EM_ETPU, "Freescale Extended Time Processing Unit"},
                                                       {ELFIO::EM_SLE9X, "Infineon Technologies SLE9X core"},
                                                       {ELFIO::EM_AVR32, "Atmel Corporation 32-bit microprocessor family"},
                                                       {ELFIO::EM_STM8, "STMicroeletronics STM8 8-bit microcontroller"},
                                                       {ELFIO::EM_TILE64, "Tilera TILE64 multicore architecture family"},
                                                       {ELFIO::EM_TILEPRO, "Tilera TILEPro multicore architecture family"},
                                                       {ELFIO::EM_MICROBLAZE, "Xilinx MicroBlaze 32-bit RISC soft processor core"},
                                                       {ELFIO::EM_CUDA, "NVIDIA CUDA architecture"},
                                                       {ELFIO::EM_TILEGX, "Tilera TILE-Gx multicore architecture family"},
                                                       {ELFIO::EM_CLOUDSHIELD, "CloudShield architecture family"},
                                                       {ELFIO::EM_COREA_1ST, "KIPO-KAIST Core-A 1st generation processor family"},
                                                       {ELFIO::EM_COREA_2ND, "KIPO-KAIST Core-A 2nd generation processor family"},
                                                       {ELFIO::EM_ARC_COMPACT2, "Synopsys ARCompact V2"},
                                                       {ELFIO::EM_OPEN8, "Open8 8-bit RISC soft processor core"},
                                                       {ELFIO::EM_RL78, "Renesas RL78 family"},
                                                       {ELFIO::EM_VIDEOCORE5, "Broadcom VideoCore V processor"},
                                                       {ELFIO::EM_78KOR, "Renesas 78KOR family"},
                                                       {ELFIO::EM_56800EX, "Freescale 56800EX Digital Signal Controller (DSC)"},
                                                       {ELFIO::EM_BA1, "Beyond BA1 CPU architecture"},
                                                       {ELFIO::EM_BA2, "Beyond BA2 CPU architecture"},
                                                       {ELFIO::EM_XCORE, "XMOS xCORE processor family"},
                                                       {ELFIO::EM_MCHP_PIC, "Microchip 8-bit PIC(r) family"},
                                                       {ELFIO::EM_INTEL205, "Reserved by Intel"},
                                                       {ELFIO::EM_INTEL206, "Reserved by Intel"},
                                                       {ELFIO::EM_INTEL207, "Reserved by Intel"},
                                                       {ELFIO::EM_INTEL208, "Reserved by Intel"},
                                                       {ELFIO::EM_INTEL209, "Reserved by Intel"},
                                                       {ELFIO::EM_KM32, "KM211 KM32 32-bit processor"},
                                                       {ELFIO::EM_KMX32, "KM211 KMX32 32-bit processor"},
                                                       {ELFIO::EM_KMX16, "KM211 KMX16 16-bit processor"},
                                                       {ELFIO::EM_KMX8, "KM211 KMX8 8-bit processor"},
                                                       {ELFIO::EM_KVARC, "KM211 KVARC processor"},
                                                       {ELFIO::EM_CDP, "Paneve CDP architecture family"},
                                                       {ELFIO::EM_COGE, "Cognitive Smart Memory Processor"},
                                                       {ELFIO::EM_COOL, "Bluechip Systems CoolEngine"},
                                                       {ELFIO::EM_NORC, "Nanoradio Optimized RISC"},
                                                       {ELFIO::EM_CSR_KALIMBA, "CSR Kalimba architecture family"},
                                                       {ELFIO::EM_Z80, "Zilog Z80"},
                                                       {ELFIO::EM_VISIUM, "Controls and Data Services VISIUMcore processor"},
                                                       {ELFIO::EM_FT32, "FTDI Chip FT32 high performance 32-bit RISC architecture"},
                                                       {ELFIO::EM_MOXIE, "Moxie processor family"},
                                                       {ELFIO::EM_AMDGPU, "AMD GPU architecture"},
                                                       {ELFIO::EM_RISCV, "RISC-V"}};

const static QMap<unsigned, QString> s_elfTypes {
    {ELFIO::ET_NONE, "None"},
    {ELFIO::ET_REL, "Relocateable object file"},
    {ELFIO::ET_EXEC, "Executable"},
    {ELFIO::ET_DYN, "Dynamically linked"},
};

// clang-format on

static QString getNameForElfMachine(unsigned machine) {
  return s_elfMachineNames.contains(machine) ? s_elfMachineNames[machine]
                                             : "Unknown";
}

static QString getNameForElfType(unsigned machine) {
  return s_elfTypes.contains(machine) ? s_elfTypes[machine] : "Unknown";
}

} // namespace Ripes
