name: Build and deploy docker image
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    if: github.repository == 'mortbopet/Ripes'
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mortbopet
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: "./docker/ripes.dockerfile"
          context: "./docker/"
          push: true
          tags: mortbopet/ripes:latest
